name: Build Notkia Kernelname: Build Kernel Packages 

on:
  push:
    branches: - master
      pull_request:
      branches: - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kódbázis letöltése
        uses: actions/checkout@v4

      - name: Build függőségek telepítése
        run: |
          echo "Függőségek telepítése..."
          sudo apt-get update
          sudo apt-get install -y build-essential 

      - name: Build futtatása
        run: |
          echo "Tesztek futtatása..."
          make test || exit 1
          
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Kódbázis letöltése
      uses: actions/checkout@v4
      
      - name: Kódminőség ellenőrzése 
        run: |
          echo "Kódminőség ellenőrzése.."
          make lint 

        deploy:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest

        steps:
          - name: Kódbázis letöltése
            uses: actions/checkout@v4

        
